---
name: Verify OpenVPN version suffix
inputs:
  image:
    description: Docker image reference to test
    required: true
  suffix:
    description: Expected suffix in OpenVPN version
    required: false
    default: longpass1
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        docker run --pull=never --rm \
          --env SUFFIX="${{ inputs.suffix }}" \
          --entrypoint sh "${{ inputs.image }}" -c '
            set -e
            openvpn --version > /tmp/version 2>&1
            head -n1 /tmp/version
            grep -q "$SUFFIX" /tmp/version
          '
